{% set name = "likeness_vitals" %}
{% set version = "1.4.9" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2de340c525538026889c07b80fbdd88eafc44fa339ca050cdefd49f60fe45b72

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 2

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - pip
  run:
    - python >={{ python_min }}
    - certifi >=2025.10.5
    - geopandas >=1.1
    - numpy >=1.26
    - pandas >=2.2
    - scipy >=1.12
    - shapely >=2.0
    - tqdm >=4.63
    - matplotlib-base >=3.7.1

test:
  imports:
    - likeness_vitals
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/likeness-pop/
  summary: Shared utilities for the Likeness ecosystem
  license: LicenseRef-UT-BATTELLE
  license_file:
    - LICENSE
    - NOTICE
  doc_url: https://github.com/likeness-pop/likeness-vitals/

extra:
  recipe-maintainers:
    - jvtcl
    - jGaboardi
